### ISSUE TITLE
mva function issue

### ISSUE THREAD

**Issue by Lucianabarros** [ahmohamed/lipidr#12] opened 2020-10-15 20:44 UTC
Hello,

great code! But mva() is not working properly for method = "PCA". It got a warning and did not work. 

Warning messages:
1: 'info.txtC = NULL' argument value is deprecated; use 'info.txtC = 'none'' instead. 
2: 'fig.pdfC = NULL' argument value is deprecated; use 'fig.pdfC = 'none'' instead. 

Thanks! 

Luciana

**Comment by ahmohamed** [comment] 2020-10-16 00:30
Hi @Lucianabarros,

Thanks for your interest in `lipidr`. Please ignore the warning, since this is because of changes in `ropls` package, and it's kept intentionally for backward compatibility. They will be probably be fixed in the next release.

Can you double check that the method did not work? You should get an `Error` if the method failed to run. If you can provide the error, I can look into why this is happening.

Ideally, can you follow the example here (https://www.lipidr.org/reference/mva.html) and see if you can reproduce the plot:
```r
mvaresults <- mva(data_normalized, measure = "Area", method = "PCA")
plot_mva(mvaresults, color_by = "group")
```

Cheers.
Ahmed.

**Comment by ahmohamed** [comment] 2020-10-20 00:23
@Lucianabarros Let me know if the issue was resolved so I can help or close the issue here.

**Closed as completed** 2020-10-29 02:58 UTC

**Comment by Lucianabarros** [comment] 2020-11-11 12:34
Sorry for the delayed response. It works on other dataset. Maybe is some issue with the data. Thank you!
