### ISSUE TITLE
error in running the Vignette example

### ISSUE THREAD

**Issue by ngoccalico** [ahmohamed/lipidr#45] opened 2022-12-05 23:19 UTC
Hi, I am trying to run your vignette but ran into a problem early on.
 line #60

```
> lipidr::list_mw_studies(keyword = "lipid")
Error: 'list_mw_studies' is not an exported object from 'namespace:lipidr'
```
Could you let me know what the problem was?

**Comment by ahmohamed** [comment] 2022-12-05 23:30
Not quite sure why it's saying that, but you should be able to run it if you load the package first with `library(lipidr)`

**Comment by ngoccalico** [comment] 2022-12-05 23:32
Yes I did that, and it is strange that it showed this error:
![image](https://user-images.githubusercontent.com/56043766/205767222-aca4ce58-165d-4b93-b6cc-b4d7b2cf8e1b.png)

**Comment by ahmohamed** [comment] 2022-12-05 23:38
I suspect lipidr is not installed correctly. What does `library('lipidr')` show?

**Comment by ngoccalico** [comment] 2022-12-05 23:57
this is what the message was 
```
> library(lipidr)
Loading required package: SummarizedExperiment
Loading required package: GenomicRanges
Loading required package: stats4
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ, clusterExport, clusterMap,
    parApply, parCapply, parLapply, parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, basename, cbind, colnames, dirname, do.call,
    duplicated, eval, evalq, Filter, Find, get, grep, grepl, intersect, is.unsorted, lapply,
    Map, mapply, match, mget, order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
    rbind, Reduce, rownames, sapply, setdiff, sort, table, tapply, union, unique, unsplit,
    which, which.max, which.min

Loading required package: S4Vectors

Attaching package: ‘S4Vectors’

The following object is masked from ‘package:base’:

    expand.grid

Loading required package: IRanges
Loading required package: GenomeInfoDb
Loading required package: Biobase
Welcome to Bioconductor

    Vignettes contain introductory material; view with 'browseVignettes()'. To cite
    Bioconductor, see 'citation("Biobase")', and for packages 'citation("pkgname")'.

Loading required package: DelayedArray
Loading required package: matrixStats

Attaching package: ‘matrixStats’

The following objects are masked from ‘package:Biobase’:

    anyMissing, rowMedians

Loading required package: BiocParallel

Attaching package: ‘DelayedArray’

The following objects are masked from ‘package:matrixStats’:

    colMaxs, colMins, colRanges, rowMaxs, rowMins, rowRanges

The following objects are masked from ‘package:base’:

    aperm, apply, rowsum

> 
```

**Comment by ngoccalico** [comment] 2022-12-05 23:59
When I tried to look for the function "list_mw_studies" it didn't show up as anything
![image](https://user-images.githubusercontent.com/56043766/205772005-7bac6255-3ffe-44f2-96ca-84006f101331.png)

**Comment by ahmohamed** [comment] 2022-12-06 00:00
Thanks for these. Try with triple colons `lipidr:::list`. Really strange.

**Comment by ngoccalico** [comment] 2022-12-06 00:02
![image](https://user-images.githubusercontent.com/56043766/205772532-5b3d3306-0466-4e5f-8a51-6d25a6f8556e.png)

I noticed the version of lipidr I have was 1.0.0, could you let me know how I can update the package?

**Comment by ahmohamed** [comment] 2022-12-06 00:08
Aah, this is too old. I didn't even ask about the version because this function was added way back. Which R version are you using? You might need to update R (4 or later) and Bioconductor versions, and simply reinstall using `BiocManager::install('lipidr')`

**Comment by ahmohamed** [comment] 2022-12-06 05:09
Closing as version was clearly the cause. Feel free to reopen if not.

**Closed as completed by ahmohamed** 2022-12-06 05:09 UTC
